# Generated by Django 2.0.2 on 2020-07-06 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
            },
        ),
        migrations.CreateModel(
            name='BowenDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('click', models.IntegerField(default=0, verbose_name='点击量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '博文数据',
                'verbose_name_plural': '博文数据',
            },
        ),
        migrations.CreateModel(
            name='BowenKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_name', models.CharField(max_length=100, verbose_name='文章类别')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='bowendb',
            name='k_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowen.BowenKind', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='banner',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowen.BowenDB', verbose_name='博文数据'),
        ),
    ]
