# Generated by Django 2.0.2 on 2020-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowenkind',
            name='kind_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类别链接'),
        ),
    ]
